// Blackout: dark and loud. Video from the gym floor, the wall sign as the headline.
window.TF_SITE = {
  optionsUrl: '/options/',
  heroVideo: 'brand/photos/gym-hero.mp4',
  heroImage: 'brand/photos/gym-community.webp',
  heroAlt: 'Training on the gym floor at Transform Fitness',
  heroEyebrow: 'The gym that actually gives a damn',
  heroTitle: ['Discipline beats', 'motivation.'],
  heroLede: 'Official Transform Fitness kit. Printed and embroidered to order, collected free from the front desk in Plympton. Wear the mindset.',
  // Section copy (TF_SITE hooks in app.js). Real facts only.
  announce: "Made to order · Official HYROX training club",
  tickerItems: ["Discipline beats motivation", "Stronger than yesterday", "HYROX training club", "Plympton, Plymouth", "Open 24/7", "Printed to order"],
  catsEyebrow: "Kit list",
  catsTitle: "Train in it",
  featEyebrow: "Core kit",
  featTitle: "Start here",
  kitEyebrow: "HYROX",
  kitTitle: "8 × 1 km. 8 stations. One kit.",
  kitLede: "Plymouth’s official HYROX training club. Top, shorts, something for your head: build it in one go.",
  printEyebrow: "The mark",
  printTitle: "Green. Silver. Black.",
  printLede: "One triangle, three colours. Pick yours, then see everything that carries it.",
  aboutEyebrow: "The gym that actually gives a damn",
  aboutTitle: "Wear the wall",
  aboutLede: "The triangle on the kit is the one on the gym wall in Plympton. Every order puts money back into the gym.",
  stepsEyebrow: "Made to order",
  stepsTitle: "No shelf. Made for you.",
  footerBlurb: "Official kit of Transform Fitness Plymouth. Discipline beats motivation.",
  gallery: {
    eyebrow: 'Race day',
    title: 'Plymouth’s HYROX club',
    lede: 'Eight kilometres, eight stations, one team. Kit built for it.',
    photos: [
      { src: 'brand/photos/ig-18312132742263049.webp', alt: 'A member pressing a sandbag overhead at a HYROX event', span: 'big' },
      { src: 'brand/photos/ig-17876169123599197.webp', alt: 'Two members with their HYROX finish time on the screen', span: 'tall' },
      { src: 'brand/photos/tf-op-enrichment.webp', alt: 'A packed group session under the Transform Fitness wall' },
      { src: 'brand/photos/tf-squat.webp', alt: 'A member back-squatting on the lifting platform' },
      { src: 'brand/photos/gym-circuits.webp', alt: 'Kettlebell work in a circuits class', span: '2' },
      { src: 'brand/photos/gym-team.webp', alt: 'Members after a group session under the Discipline Beats Motivation sign', span: '2' },
    ],
  },
};
