// Field: olive, utilitarian, kit-list. Built around the olive tees and MOLLE packs.
window.TF_SITE = {
  optionsUrl: '/options/',
  heroImage: 'brand/photos/gym-more-than-gym.webp',
  heroAlt: 'Two members talking between sets in front of the OSB wall',
  heroEyebrow: 'Official kit · Langage, Plympton · 2 min off the A38',
  heroTitle: ['Built for', 'the work.'],
  heroLede: 'Olive tri-blend tees, MOLLE packs, recycled shorts. Printed and embroidered to order, collected from the front desk.',
  noTicker: true,
  // Section copy (TF_SITE hooks in app.js). Real facts only.
  announce: "Made to order · Free collection · UK delivery free over £60",
  catsEyebrow: "Inventory",
  catsTitle: "Kit list",
  featEyebrow: "Standard issue",
  featTitle: "The working kit",
  featured: ["back-mark-tee", "classic-hoodie", "heavyweight-crew", "training-shorts", "molle-backpack-35", "molle-backpack-25", "patch-beanie", "padded-gilet"],
  kitEyebrow: "Race-day loadout",
  kitTitle: "HYROX loadout",
  kitLede: "Transform Fitness is Plymouth’s official HYROX training club. Top, shorts, headwear: spec it in one go.",
  printEyebrow: "Mark spec",
  printTitle: "Three marks",
  printLede: "Green, silver or black triangle. Pick the mark, see every piece it comes on.",
  aboutEyebrow: "Base",
  aboutTitle: "Langage, Plympton",
  aboutLede: "Transform Fitness is an independent gym two minutes off the A38. The kit carries the triangle from the wall, and every order supports the gym.",
  stepsEyebrow: "Procedure",
  stepsTitle: "Order. Make. Collect.",
  footerBlurb: "Official kit of Transform Fitness Plymouth. Printed and embroidered to order in 10 to 15 days.",
  gallery: {
    eyebrow: 'Field notes',
    title: 'Where it gets used',
    lede: 'Circuits, strength, HYROX. The kit goes where the members go.',
    photos: [
      { src: 'brand/photos/gym-circuits.webp', alt: 'Kettlebell work in a circuits class', span: 'tall' },
      { src: 'brand/photos/ig-18312132742263049.webp', alt: 'A member pressing a sandbag overhead at a HYROX event', span: 'big' },
      { src: 'brand/photos/gym-community.webp', alt: 'The gym floor: black and green racks and free weights' },
      { src: 'brand/photos/tf-squat.webp', alt: 'A member back-squatting on the lifting platform' },
      { src: 'brand/photos/gym-team.webp', alt: 'Members after a group session under the Discipline Beats Motivation sign', span: 'wide' },
    ],
  },
};
