// Chalk: light editorial. Real photography framed like a lookbook.
window.TF_SITE = {
  optionsUrl: '/options/',
  heroImage: 'brand/photos/tf-group-team.webp',
  heroAlt: 'Members gathered under the Transform Fitness wall after a group session',
  heroEyebrow: 'Official kit · Transform Fitness Plymouth',
  heroTitle: ['Kit for', 'the People’s Gym.'],
  heroLede: 'Tees, hoodies and vests printed or embroidered to order in Plympton. The same triangle you train under, made properly.',
  noTicker: true,
  galleryFirst: true,
  // Section copy (TF_SITE hooks in app.js). Real facts only.
  announce: "Made to order in Plympton · Free collection, or UK delivery free over £60",
  catsEyebrow: "The collection",
  catsTitle: "Shop by piece",
  featEyebrow: "Edited",
  featTitle: "The essentials",
  kitEyebrow: "Race day",
  kitTitle: "Dressed for HYROX",
  kitLede: "Transform Fitness is Plymouth’s official HYROX training club. Put together a top, shorts and something for your head, in one go.",
  printEyebrow: "The mark",
  printTitle: "One triangle, three finishes",
  printLede: "Green, silver or black. Choose the finish first, then see every piece that carries it.",
  aboutLede: "An independent gym in Plympton, open since November 2025. The kit carries the triangle from the wall, and every order supports the gym.",
  gallery: {
    eyebrow: 'From the floor',
    title: 'No egos. No judgement.',
    lede: 'Real people getting real results, together. Every order supports the gym.',
    photos: [
      { src: 'brand/photos/gym-community.webp', alt: 'The gym floor at Transform Fitness: black and green racks and free weights', span: 'big' },
      { src: 'brand/photos/tf-squat.webp', alt: 'A member back-squatting on the lifting platform', span: 'tall' },
      { src: 'brand/photos/gym-team.webp', alt: 'Members after a group session under the Discipline Beats Motivation sign' },
      { src: 'brand/photos/gym-circuits.webp', alt: 'Kettlebell work in a circuits class' },
      { src: 'brand/photos/gym-more-than-gym.webp', alt: 'Two members talking between sets', span: '2' },
      { src: 'brand/photos/ig-17876169123599197.webp', alt: 'Two members with their HYROX finish time on the screen' },
      { src: 'brand/photos/tf-cosmo.webp', alt: 'Cosmo, the gym dog, in a Transform Fitness cap', caption: 'Cosmo · head of morale' },
    ],
  },
};
