// People: warm, community-first. Members' photos everywhere, the dog in the footer.
window.TF_SITE = {
  optionsUrl: '/options/',
  heroImage: 'brand/photos/tf-op-enrichment.webp',
  heroAlt: 'A packed group session under the Transform Fitness wall',
  heroEyebrow: 'By members, for members',
  heroTitle: ['Made for', 'the People’s Gym.'],
  heroLede: 'Every piece is printed or embroidered to order and collected at the front desk in Plympton. No egos. No judgement. Just good kit.',
  noTicker: true,
  galleryFirst: true,
  // Section copy (TF_SITE hooks in app.js). Real facts only.
  announce: "Made to order for The People’s Gym · Pick it up free at the front desk",
  catsEyebrow: "Find your fit",
  catsTitle: "Something for every session",
  featEyebrow: "Start here",
  featTitle: "The staples",
  kitEyebrow: "Race day",
  kitTitle: "Racing HYROX with the club?",
  kitLede: "We’re Plymouth’s official HYROX training club. Put your race kit together in one go: a top, shorts and something for your head.",
  printEyebrow: "Your colour",
  printTitle: "Green, silver or black?",
  aboutEyebrow: "The People’s Gym",
  aboutTitle: "The gym that actually gives a damn",
  aboutLede: "No egos. No judgement. An independent gym in Plympton, and every kit order supports it.",
  stepsTitle: "Ordered by you, made for you",
  gallery: {
    eyebrow: 'Our lot',
    title: 'Everyone knows your name',
    lede: 'Sunday sessions, race days, and Cosmo on the mat. This is who the kit is for.',
    photos: [
      { src: 'brand/photos/gym-team.webp', alt: 'Members after a group session under the Discipline Beats Motivation sign', span: 'big', caption: 'Discipline beats motivation' },
      { src: 'brand/photos/ig-17876169123599197.webp', alt: 'Two members with their HYROX finish time on the screen', span: 'tall', caption: '1:01:19 · HYROX doubles' },
      { src: 'brand/photos/gym-more-than-gym.webp', alt: 'Two members talking between sets' },
      { src: 'brand/photos/tf-cosmo.webp', alt: 'Cosmo, the gym dog, in a Transform Fitness cap', caption: 'Cosmo · head of morale' },
      { src: 'brand/photos/tf-group-team.webp', alt: 'Members gathered under the Transform Fitness wall', span: '2' },
      { src: 'brand/photos/ig-18103922803815852.webp', alt: 'Cosmo sitting on the Transform Fitness mat' },
      { src: 'brand/photos/gym-circuits.webp', alt: 'Kettlebell work in a circuits class' },
    ],
  },
};
