"""Hand-curated product families over the 35 DecoNetwork listings.

Each Deco listing (x colour) becomes one variant of a family. Copy is written
from the supplier specs scraped off each product page; nothing is invented
beyond the family name and the one-line pitch.
"""
GREEN, SILVER, BLACK, NONE = 'green', 'silver', 'black', 'none'

CATEGORIES = [
    # slug, label, blurb
    ('tees', 'Tees', 'Tri-blend tees and wicking long sleeves.'),
    ('vests', 'Vests', 'Performance and cotton vests for heavy sessions.'),
    ('bras', 'Sports bras', 'Medium support, cross-back straps.'),
    ('hoodies', 'Hoodies', 'Classic pullovers and a technical zip-through.'),
    ('sweats', 'Sweatshirts', 'Heavyweight crews with an embroidered mark.'),
    ('shorts', 'Shorts', 'Recycled stretch shorts with a built-in liner.'),
    ('outerwear', 'Gilets', 'Padded, showerproof, windproof.'),
    ('headwear', 'Headwear', 'Caps, beanies and a neck tube.'),
    ('bags', 'Bags', 'Holdall and MOLLE backpacks.'),
]

# variant spec: (deco_id, label, garment colour name override or None, logo tone, print summary)
FAMILIES = [
    dict(slug='back-mark-tee', name='Back Mark Tee', cat='tees', code='CV3413', featured=1,
         pitch='The one from the gym wall. A small mark on the chest and the full triangle across your back.',
         prints=['Chest mark', 'Full back print'],
         variants=[('28746341', 'Black / Green', None, GREEN), ('28746346', 'Olive / Silver', None, SILVER), ('28793601', 'Olive / Black', None, BLACK)],
         features=['Bella+Canvas tri-blend: 50% polyester, 25% Airlume combed ringspun cotton, 25% rayon', 'Retail fit', 'Ribbed collar, taped neck and shoulders', 'Side seams, twin-needle sleeves and hem', 'Tear-out label']),
    dict(slug='team-tee', name='Team Tee', cat='tees', code='CV3413', featured=4,
         pitch='Chest mark up front and TEAM TRANSFORM FITNESS across the shoulders.',
         prints=['Chest mark', 'Team wordmark across the upper back'],
         variants=[('28745311', 'Black / Green', None, GREEN), ('28746041', 'Olive / Silver', None, SILVER), ('28793596', 'Olive / Black', None, BLACK)],
         features=['Bella+Canvas tri-blend: 50% polyester, 25% Airlume combed ringspun cotton, 25% rayon', 'Retail fit', 'Ribbed collar, taped neck and shoulders', 'Side seams, twin-needle sleeves and hem', 'Tear-out label']),
    dict(slug='essential-tee', name='Essential Tee', cat='tees', code='CV3413', featured=0,
         pitch='Just the mark, left chest. Soft tri-blend that works in the gym and out of it.',
         prints=['Chest mark'],
         variants=[('28775316', 'Black / Green', None, GREEN), ('28793496', 'Olive / Silver', None, SILVER), ('28793506', 'Olive / Black', None, BLACK)],
         features=['Bella+Canvas tri-blend: 50% polyester, 25% Airlume combed ringspun cotton, 25% rayon', 'Retail fit', 'Ribbed collar, taped neck and shoulders', 'Side seams, twin-needle sleeves and hem', 'Tear-out label']),
    dict(slug='cool-long-sleeve', name='Cool Long Sleeve', cat='tees', code='JC002', featured=0,
         pitch='Lightweight wicking long sleeve with UPF 30+. Pick your print.',
         prints=['Chest mark', 'Optional back print'],
         variants=[('28793481', 'Chest mark', None, GREEN), ('28764181', 'Team back', None, GREEN), ('28793466', 'Back mark', None, GREEN)],
         features=['AWDis Just Cool Neoteric textured fabric that wicks sweat', 'UPF 30+ UV protection', 'Self-fabric collar and cuffs', 'Taped back neck', 'Twin-needle stitching']),
    dict(slug='performance-vest', name='Performance Vest', cat='vests', code='02073', featured=3,
         pitch='Breathable textured polyester that stays light when the session gets long.',
         prints=['Mark on the front, or the Team wordmark on the back'],
         variants=[('28816471', 'Green centre', None, GREEN), ('28816496', 'Silver centre', None, SILVER), ('28816461', 'Green chest', None, GREEN), ('28764101', 'Team back', None, GREEN)],
         features=["SOL'S Sporty: 100% polyester", 'Textured, breathable fabric', 'Self-fabric bound neck and armholes', 'Side seams, twin-needle hem', 'Tear-out label']),
    dict(slug='cotton-tank', name='Cotton Tank', cat='vests', code='11465', featured=0,
         pitch='Ringspun cotton tank with a green chest mark. Goes up to 5XL.',
         prints=['Chest mark'],
         variants=[('28817406', 'Deep Black', None, GREEN)],
         features=["SOL'S Justin: 100% ringspun semi-combed cotton", 'Ribbed bound neckline and armholes', 'Tubular body', 'Twin-needle hem']),
    dict(slug='core-sports-bra', name='Core Sports Bra', cat='bras', code='TL371', featured=5,
         pitch='Medium support with a cross-over back and a permanent cup insert.',
         prints=['Centre mark'],
         variants=[('28776066', 'Green mark', None, GREEN), ('28764281', 'Silver mark', None, SILVER)],
         features=['Tombo: 86% polyester, 14% elastane interlock', 'Medium support', 'Cross-over elastic back straps, adjustable', 'Elastic band with bra clasp closure', 'Permanent cup insert', 'Tear-out label']),
    dict(slug='classic-hoodie', name='Classic Hoodie', cat='hoodies', code='UC502', featured=2,
         pitch='Brushed-back 50/50 pullover with a double hood. Sizes XS to 6XL.',
         prints=['Chest monogram, or the full mark on the Silver version'],
         variants=[('28793541', 'Black / Green', None, GREEN), ('28793536', 'Military Green / Black', None, BLACK), ('28817636', 'Black / Silver mark', None, SILVER)],
         features=['Uneek: 50% polyester, 50% cotton, reactive dyed', 'Brushed inside for a soft handle', 'Double-fabric hood with self-coloured cord', 'Lycra ribbed cuffs and welt', 'Front pouch pocket', 'Taped neck, twin-needle stitching']),
    dict(slug='tech-zip-hoodie', name='Technical Zip Hoodie', cat='hoodies', code='TL578', featured=0,
         pitch='Four-way stretch zip-through with zipped pockets and the Team wordmark on the back.',
         prints=['Chest mark', 'Team wordmark across the back'],
         variants=[('28764871', 'Black', None, GREEN)],
         features=['Tombo four-way stretch microfibre', 'Raglan sleeves, three-panel hood', 'Funnel neck with sports toggles', 'Full-length reverse zip with snap-down pull', 'Two zipped front pockets', 'Drop hem']),
    dict(slug='heavyweight-crew', name='Heavyweight Crew', cat='sweats', code='JH123', featured=6,
         pitch='Oversized, cotton-faced and brushed inside. The monogram is embroidered, not printed.',
         prints=['Embroidered chest monogram'],
         variants=[('28764456', 'Deep Black / Green', None, GREEN), ('28776051', 'Earthy Green / Black', None, BLACK)],
         features=['AWDis Signature: 70% ringspun cotton, 20% polyester, 10% recycled polyester', 'Cotton-faced fabric with brushed-back fleece', 'Drop shoulder, oversized fit', 'Ribbed collar, cuffs and hem', 'Tear-out label']),
    dict(slug='training-shorts', name='Training Shorts', cat='shorts', code='SR780M', featured=7,
         pitch='Quick-dry stretch shorts with a built-in liner and zipped side pockets.',
         prints=['Leg mark'],
         variants=[('28776046', 'Green mark', None, GREEN), ('28764801', 'Silver mark', None, SILVER)],
         features=['Spiro recycled hi-tech stretch fabric', 'Quick-dry and breathable', 'Integrated inner shorts with pocket', 'Two zipped side pockets', 'Elasticated waistband with drawcord', 'Side vents, tag-free']),
    dict(slug='padded-gilet', name='Compass Padded Gilet', cat='outerwear', code='RS238', featured=0,
         pitch='Recycled padded gilet with soft-shell side panels. Showerproof and windproof.',
         prints=['Chest monogram'],
         variants=[('28817341', 'Black', None, GREEN)],
         features=['Result Recycled: recycled polyester outer and Repreve recycled padding', 'Micro-fleece inner layer', 'Stretch soft-shell inserts on shoulders and sides', 'Showerproof, windproof, breathable', 'Stand-up padded collar, chin guard', 'Full-length zip and zipped chest pocket']),
    dict(slug='patch-beanie', name='Patch Beanie', cat='headwear', code='BB442R', featured=0,
         pitch='Ribbed, cuffed beanie with a woven-look mark patch.',
         prints=['Front patch'],
         variants=[('28816736', None, None, GREEN)],
         features=['Beechfield: 52% recycled polyester, 47% acrylic, 1% elastane', 'Ribbed single-layer knit', 'Cuffed design', 'Cotton twill patch, 6.5 × 3 cm', 'Tear-out label']),
    dict(slug='air-mesh-cap', name='Air Mesh Cap', cat='headwear', code='BB196M', featured=0,
         pitch='Six-panel cap with ventilation eyelets and the green monogram.',
         prints=['Front monogram'],
         variants=[('28816431', 'Black', None, GREEN)],
         features=['Beechfield Air Mesh six-panel design', 'Structured front panels', 'Stitched ventilation eyelets', 'Pre-curved peak, cotton twill underpeak and sweatband', 'Self-fabric strap with tri-glide buckle']),
    dict(slug='multicam-trucker', name='Multicam Trucker', cat='headwear', code='F6606MC', featured=0,
         pitch='Flexfit retro trucker in Multicam Black with a tonal mark.',
         prints=['Front mark'],
         variants=[('28764601', 'Black Multicam', None, BLACK)],
         features=['Flexfit: 98% cotton, 2% elastane', 'Six panel, mid profile', 'Structured front panels, curved peak', 'Mesh rear panels', 'Plastic snapback adjuster']),
    dict(slug='morf-neck-tube', name='Morf Neck Tube', cat='headwear', code='BB900', featured=0,
         pitch='Seam-free microfibre tube for cold runs. Wear it as a snood, headband or cap.',
         prints=['Unbranded'],
         variants=[('28816571', None, None, NONE)],
         features=['Beechfield Morf Original: 100% polyester microfibre', 'Breathable and seam-free', 'Machine washable, no ironing', '50 × 25 cm']),
    dict(slug='training-holdall', name='Training Holdall', cat='bags', code='BG561', featured=0,
         pitch='32-litre holdall with a shoe tunnel for the wet kit.',
         prints=['Front monogram'],
         variants=[('28763626', 'Black', None, GREEN)],
         features=['BagBase: 100% recycled 600D polyester', '32 litres, 25 × 50 × 26 cm', 'Shoe tunnel / wet pocket', 'Two-way main zip, front zip pocket', 'Detachable padded shoulder strap', 'PU-coated base panel']),
    dict(slug='molle-backpack-35', name='MOLLE Backpack 35L', cat='bags', code='BG850', featured=0,
         pitch='Military-inspired 35-litre pack with a padded laptop sleeve.',
         prints=['Unbranded'],
         variants=[('28764851', None, None, NONE)],
         features=['BagBase 600D polyester, 210D lining', '48 × 31 × 24 cm', 'MOLLE webbing and dual Rip-Strip front pocket', 'Padded laptop compartment', 'Padded adjustable straps and chest strap', 'Compression straps, internal mesh pockets']),
    dict(slug='molle-backpack-25', name='MOLLE Backpack 25L', cat='bags', code='BG848', featured=0,
         pitch='The everyday version: 25 litres with two front zip pockets.',
         prints=['Unbranded'],
         variants=[('28763641', None, None, NONE)],
         features=['BagBase 600D polyester', '25 litres, 45 × 30 × 22 cm', 'MOLLE webbing and dual Rip-Strip', 'Two front zip pockets, internal slip pocket', 'Padded back panel and straps', 'Compression straps']),
]
